language: node_js
node_js:
- '8'
- '10'
script:
- npm test
notifications:
  slack:
    on_pull_requests: false
    rooms:
      secure: bKiOrBe1gYfqC0q2DPz97UW+tY8UKzbpKo8W5o8rsm5Niq2pFBNoWjHTLGOsjUlPPkmkBK3xjr2RiWMM3CvIe4fm4o8aap2tubjd4pubqMfBqEDZWlOlOQI7ZirKBhAflXIAp+CEDl4up/QBnWpq8K11/xgYgGD2CNrvp4KPfiHZzmyxXmNqgU05rt75cPbd3cYpQ0BudwNIcbVlsVkvWYc/OG8Wl4ItRfcvIjnjTqNaWaasEvcm+ljPTJ00cbcFWJdwlqIkfrMufosdyEYGaSyxHfVo+JTlSh6NSTkMt9Go64/qjVxFtnBc8nhhFx88e1Nu1UiBCLu0TH9x4Tmk4lKxcrCIW6xbomiwhS578EWWbtRjXESvwOw1c7YFXg+T3dLOgp13FiGCOqNhz5J6uWSAcavU/T22RPyNPrEaFpiYrEz5qQmnFJjvHIjybr+xH6ePdLb/QtJG7mtWfLenJRD6AZhroAPLEVZdLJ++dEM9UMouEX0pUlNYEAulREFfVc1H0/l2kcE91ZA3mCIEH3L2mlbxqJW4DmfmOGatAqHVgnQv6YXsbXPEVK4xrYJUl+PkilXjjDzd4gxfPLT49NDCCl+ysYfEH+wItH2uJj2x9zj4/wYpigjucENzi6ERse5xx2jnQpCAAed2RXXXTX2h1caO+Hp8xr9UEuMnGfI=
  email: false
deploy:
  provider: npm
  email: guy@thebigsurf.co.uk
  api_key:
    secure: IEwmUcnZAnPxuEk7hro8/cElZ/kXK6b9ubqJwdtbd/RSndeyR/uY5fJxuI4EYtTK+0BKdux9TUMfjkv1ex8fyIhBbRZ8dS3zRLRH+94ZP+8Jm1h9LSiPGfRnzKOQ4YaIloXRSzZJdeHgwHKC6TFrqjgW9B4Yl4NQA9Wrz4TDmU7qEOvKAUp/6eAhd3UZL3L6x4zFgwbt3nv3LJYiO+MX2eDtFutSHzJTrRNFdndPxChaev4W81E0OHo9HYngvoSbsWm217IpBL+9H69+NiLWrB87ttSqa0ujQKwsx6nkQ3cdoz+I8hl2GeSjiMAKOO2ZtWwUyIi9z49szLnWxIUO9tb0QknXBoCFTSh7Ky/ztxDcY5Syi3SGD1KGF8Pje6qc7KB4TXyQB5g2X65Lk6+d8AKJRJDGIz8YJPQQutUt7D5Mu+3TVvfCAsI3kO0/xJK7YDQGRZQ+wew6CHDXncMZR4HM0PEIzUfOEE11Nd6FX5xVQR3x/DlutKf/MuF5ovV7liXZQR6AosCTV2KqgFCz32VMRV8XGrYoCvCD/+Eosg2oJJjssc34STub5u4eZIfLeQH9Tvkly4IZedAv+UBmGIU2EDayN/g67J1uonSR3xf+qwbW/0+6kPyZ2ZeBnH499I8ri6OdlbvV2pQbvShQqBp2yyCJxv8oVn7IyQyW9sM=
  on:
    tags: true
    repo: theGC/html-webpack-inline-svg-plugin
  skip_cleanup: 'true'
